name: sqlite3
version: '3.20.0' 
summary: Library implementing a self-contained, serverless, transactional database
description: |
  SQLite is an embedded SQL database engine. Unlike most other SQL databases, SQLite does not have a separate server process. SQLite reads 
  and writes directly to ordinary disk files. A complete SQL database with multiple tables, indices, triggers, and views, is contained 
  in a single disk file. The database file format is cross-platform - you can freely copy a database between 32-bit and 64-bit systems 
  or between big-endian and little-endian architectures. These features make SQLite a popular choice as an Application File Format. 
  Think of SQLite not as a replacement for Oracle but as a replacement for fopen()

grade: devel 
confinement: devmode 

apps:
  sqlite3:
    command: bin/sqlite3
    

parts:
  sqlite3:
    plugin: autotools
    source-type: tar
    source: https://www.sqlite.org/snapshot/sqlite-snapshot-201707171241.tar.gz
